tasks:
  - init: |
      sudo apt update
      sudo apt install -y curl unzip
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip -q awscliv2.zip
      sudo ./aws/install
      aws --version
      git config --global user.email "pawarharsha474@gmail.com"
      git config --global user.name "Harsha"
  - command: |
      while true; do
        git add -A
        git commit -m "Auto-commit: $(date)" || echo "Nothing to commit"
        git push || echo "Push failed"
        sleep 300
      done
