# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
    name: aws-cli
    env:
    AWS_CLI_AUTO_PROMPT:on-partial
    before: 
    cd /workspace
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install
    cd $THEIA_WORKSPACE_ROOT
    export AWS_ACCESS_KEY_ID=AKIAVXDKZB3GXLYW2FPV
    export AWS_SECRET_ACCESS_KEY=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
    export AWS_DEFAULT_REGION=us-west-1

